# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iGoat-Swift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iGoat-Swift
  pod 'RealmSwift', '10.7.6'
#  pod 'CouchbaseLite-Swift', '3.0.0'
#  pod 'CouchbaseLite', '2.5.0'

  target 'iGoat-SwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
