# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iGoat-Swift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'YapDatabase'
  pod 'CouchbaseLite-Swift'
  pod 'RealmSwift'
  # Pods for iGoat-Swift

  target 'iGoat-SwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
